### ISSUE TITLE
Accessible modal

### ISSUE THREAD

**Issue by AmirhosseinHashemi** [ShahramShakiba/Modal#1]
well done Shahram 🎉.

It's good to close modal with _Esc_ button on keyboard and good for accessibility.
If you like you can add below code to your project :

```
document.addEventListener('keydown', function (e) {
  if (e.key === 'Escape' && !modal.classList.contains('hidden')) {
    closeModal();
  }
});
```

**Comment by ShahramShakiba** [comment]
I appreciated your consideration and precision you gave to my codes, and I must say that you pointed out a good detail and I will implement it.
Thanks Amirhossein
